const data = {
	products: [
		{
			_id: "1",
			productName: "Nike",
			category: "",
			poster: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
			price: 120,
			sale: false,
			salePrice: 0,
			countInStock: 12,
			brand: "Nike",
			rate: 4.5,
			description: "High quality product",
		},
		{
			_id: "2",
			productName: "Adidas",
			category: "",
			poster: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
			price: 120,
			sale: true,
			salePrice: 80.99,
			countInStock: 12,
			brand: "Nike",
			rate: 0,
			description: "High quality product",
		},
		{
			_id: "3",
			productName: "vans",
			category: "",
			poster: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
			price: 120,
			sale: true,
			salePrice: 80.99,
			countInStock: 12,
			brand: "Vans",
			rate: 3,
			description: "High quality product",
		},
		{
			_id: "4",
			productName: "Reebook",
			category: "",
			poster: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
			price: 99.99,
			sale: false,
			salePrice: 80.99,
			brand: "Reebook",
			countInStock: 12,
			rate: 2.5,
			description: "High quality product",
		},
		{
			_id: "5",
			productName: "Reebook",
			category: "",
			poster: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
			price: 99.99,
			sale: false,
			salePrice: 80.99,
			brand: "Reebook",
			countInStock: 12,
			rate: 2.5,
			description: "High quality product",
		},
	],
};

export default data;
